// USERS
export const GET_USERS = "GET_USERS";
export const GET_USERS_SUCCESSFULLY = "GET_USERS_SUCCESSFULLY";
export const GET_USERS_ERROR = "GET_USERS_ERROR";

// COLOR
export const GET_COLOR = "GET_COLOR";
export const GET_COLOR_SUCCESSFULLY = "GET_COLOR_SUCCESSFULLY";
export const GET_COLOR_ERROR = "GET_COLOR_ERROR";
